# Lamplit Core/Full application image.
#
# The generated `.build/plugins` directory is populated by the Dagger module
# from immutable public commits. Direct Docker builds must prepare those
# tarballs first; release builds always run through `dagger call check`.
ARG NODE_IMAGE=node:24.20.0-bookworm-slim@sha256:6642ef280aebc09c4541bee0b15c9f89f0f3f3c247ddee79ae1d37eddfdcbbaa
FROM ${NODE_IMAGE}

ARG VARIANT=core
ARG LAMPLIT_VERSION=0.1.0
ARG LAMPLIT_REVISION=dev
ARG DSH_VERSION=0.1.2-rc.1
ARG COMPANION_VERSION=0.2.3
ARG SPEECH_VERSION=0.2.4
ARG GUION_WEB_VERSION=0.6.2
ARG HINDSIGHT_VERSION=0.2.0
ARG IMAGEGEN_VERSION=0.4.0
ARG LAMPLIT_SOURCE=https://github.com/LamplitIsles/lamplit
ARG LAMPLIT_LICENSE=Elastic-2.0

ENV NODE_ENV=production \
    DSH_HOME=/home/lamplit/.local/state/dsh \
    HOME=/home/lamplit \
    LAMPLIT_VARIANT=${VARIANT} \
    PATH=/opt/guion-web/node_modules/.bin:/opt/dsh-runtime/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

USER root
RUN apt-get update \
    && apt-get install --yes --no-install-recommends ca-certificates git \
    && npm install --global --no-audit --no-fund pnpm@11.22.0 \
    && rm -rf /var/lib/apt/lists/* \
    # The pinned Node base already reserves uid/gid 1000 for its `node`
    # account. Reuse that fixed non-root identity when present; otherwise
    # create the Lamplit account without making the build depend on a name.
    && if ! getent group 1000 >/dev/null; then groupadd --gid 1000 lamplit; fi \
    && if ! getent passwd 1000 >/dev/null; then useradd --uid 1000 --gid 1000 --create-home --home-dir /home/lamplit --shell /usr/sbin/nologin lamplit; fi \
    && install -d -o 1000 -g 1000 -m 0700 /home/lamplit/.local/state/dsh \
      /home/lamplit /workspace /var/lib/lamplit/keet /opt/lamplit/seed-state \
      /opt/dsh-runtime /tmp

# Runtime dependencies are installed with npm's lockfile in the image build
# context. `npm ci` keeps every resolved transitive package reproducible.
COPY docker/lamplit/runtime-package.json /opt/dsh-runtime/package.json
COPY docker/lamplit/runtime-package-lock.json /opt/dsh-runtime/package-lock.json
RUN npm ci --prefix /opt/dsh-runtime --omit=dev --ignore-scripts --no-audit --no-fund \
    && npm rebuild --prefix /opt/dsh-runtime --omit=dev --no-audit --no-fund \
    && chown -R 1000:1000 /opt/dsh-runtime

# The plugin tarballs are generated by Dagger. A normal Docker context may
# leave the directory empty; the full release path always supplies both files.
COPY .build/plugins/ /tmp/plugins/
RUN npm install --prefix /opt/guion-web --omit=dev --ignore-scripts --no-audit --no-fund /tmp/plugins/guionai-web.tgz \
    && chown -R 1000:1000 /opt/guion-web
COPY docker/lamplit/entrypoint.sh /usr/local/bin/lamplit-entrypoint
COPY docker/lamplit/proxy.mjs /usr/local/bin/lamplit-proxy.mjs
COPY docker/lamplit/launcher.mjs /usr/local/bin/lamplit-launcher.mjs
COPY docker/lamplit/settings.example.yaml /opt/lamplit/settings.example.yaml
COPY docker/lamplit/profile.patch.example.yml /opt/lamplit/profile.patch.example.yml
COPY docker/lamplit/hindsight.example.json /opt/lamplit/hindsight.json
COPY docker/lamplit/capabilities.core.json /opt/lamplit/capabilities.core.json
COPY docker/lamplit/capabilities.full.json /opt/lamplit/capabilities.full.json
COPY LICENSE /usr/share/doc/lamplit/LICENSE
COPY NOTICE /usr/share/doc/lamplit/NOTICE
COPY THIRD_PARTY_NOTICES.md /usr/share/doc/lamplit/THIRD_PARTY_NOTICES.md
COPY licenses/ /usr/share/doc/lamplit/licenses/
COPY sbom/lamplit.spdx.json /usr/share/doc/lamplit/sbom.spdx.json
RUN chmod 0555 /usr/local/bin/lamplit-entrypoint \
    && if [ "$VARIANT" = full ]; then cp /opt/lamplit/capabilities.full.json /opt/lamplit/capabilities.json; else cp /opt/lamplit/capabilities.core.json /opt/lamplit/capabilities.json; fi \
    && mkdir -p /opt/lamplit/seed-state/profiles/web \
    # pnpm 11 requires an explicit allow-list for native package build
    # scripts. Guion Web's image path uses sharp; keep the allow-list inside
    # the image-owned profile so sync is deterministic at build and runtime.
    && printf 'packages:\n  - .\nnodeLinker: hoisted\nautoInstallPeers: false\nallowBuilds:\n  sharp: true\n' > /opt/lamplit/seed-state/profiles/web/pnpm-workspace.yaml \
    && DSH_HOME=/opt/lamplit/seed-state dsh plugin --profile web add \
      @guionai/dsh-web@${GUION_WEB_VERSION} \
      @lamplitisles/dsh-companion@${COMPANION_VERSION} \
      @lamplitisles/kepos-speech@${SPEECH_VERSION} \
      /tmp/plugins/lamplitisles-dsh-mail.tgz \
      /tmp/plugins/lamplitisles-dsh-keet.tgz \
      $(if [ "$VARIANT" = full ]; then printf '%s\n' "@lamplitisles/kepos-hindsight@${HINDSIGHT_VERSION}" "@lamplitisles/dsh-imagegen@${IMAGEGEN_VERSION}"; fi) \
    && DSH_HOME=/opt/lamplit/seed-state web dsh sync --yes \
    && DSH_HOME=/opt/lamplit/seed-state web dsh doctor \
    # The Loader imports profile plugins from the launcher's installation
    # anchor under plain Node. Keep those package entries image-owned and
    # stable while the user profile remains independently writable.
    && for package in \
      @guionai/dsh-web \
      @lamplitisles/dsh-companion \
      @lamplitisles/dsh-keet \
      @lamplitisles/dsh-mail \
      @lamplitisles/kepos-speech; do \
        mkdir -p "/opt/dsh-runtime/node_modules/$(dirname "$package")"; \
        ln -s "/opt/lamplit/seed-state/profiles/web/node_modules/$package" "/opt/dsh-runtime/node_modules/$package"; \
      done \
    # The profile packages declare the DSH runtime as peer dependencies. The
    # image-owned scope link gives Node's ordinary ESM resolver the same
    # installation closure that DSH's module fallback describes.
    && ln -s /opt/dsh-runtime/node_modules/@deepseek-ai /opt/lamplit/seed-state/profiles/web/node_modules/@deepseek-ai \
    && if [ "$VARIANT" = full ]; then \
      for package in @lamplitisles/kepos-hindsight @lamplitisles/dsh-imagegen; do \
        mkdir -p "/opt/dsh-runtime/node_modules/$(dirname "$package")"; \
        ln -s "/opt/lamplit/seed-state/profiles/web/node_modules/$package" "/opt/dsh-runtime/node_modules/$package"; \
      done; \
    fi \
    && if [ "$VARIANT" = full ]; then cp /opt/lamplit/hindsight.json /opt/lamplit/seed-state/hindsight.json; fi \
    && find /opt/lamplit/seed-state -type f -name '*.lock' -exec chmod 0600 {} + \
    && chown -R 1000:1000 /opt/lamplit /home/lamplit /workspace /var/lib/lamplit \
    && chmod 0755 /opt/lamplit /opt/lamplit/seed-state \
    && chmod 0555 /usr/local/bin/lamplit-proxy.mjs /usr/local/bin/lamplit-launcher.mjs

LABEL org.opencontainers.image.title="Lamplit ${VARIANT}" \
      org.opencontainers.image.description="${VARIANT} Lamplit self-hosted Partner distribution" \
      org.opencontainers.image.source="${LAMPLIT_SOURCE}" \
      org.opencontainers.image.licenses="${LAMPLIT_LICENSE}" \
      org.opencontainers.image.version="${LAMPLIT_VERSION}" \
      org.opencontainers.image.revision="${LAMPLIT_REVISION}" \
      org.opencontainers.image.vendor="LamplitIsles community distribution" \
      org.opencontainers.image.variant="${VARIANT}" \
      io.lamplit.dsh.version="${DSH_VERSION}" \
      io.lamplit.third-party-notices="/usr/share/doc/lamplit/THIRD_PARTY_NOTICES.md" \
      io.lamplit.sbom="/usr/share/doc/lamplit/sbom.spdx.json" \
      io.lamplit.third-party-licenses="MIT,Apache-2.0"

VOLUME ["/home/lamplit/.local/state/dsh", "/workspace", "/var/lib/lamplit/keet"]
EXPOSE 3080
USER 1000:1000
ENTRYPOINT ["/usr/local/bin/lamplit-entrypoint"]
